# Generated by Django 5.2.17 on 2026-09-12 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_workspace_region_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام رنج')),
                ('activity_scope', models.CharField(choices=[('all', 'فروش و اجاره'), ('sale', 'فقط فروش'), ('rent', 'فقط اجاره')], default='all', max_length=20, verbose_name='حوزه فعالیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_ranges', to=settings.AUTH_USER_MODEL, verbose_name='مدیر رنج')),
                ('regions', models.ManyToManyField(blank=True, related_name='ranges', to='locations.region', verbose_name='مناطق مجاز')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'رنج',
                'verbose_name_plural': 'رنج\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RangeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ranges.range', verbose_name='رنج')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='range_membership', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_memberships', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'عضویت در رنج',
                'verbose_name_plural': 'عضویت\u200cهای رنج',
            },
        ),
        migrations.AddIndex(
            model_name='range',
            index=models.Index(fields=['workspace', 'is_active'], name='range_workspace_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_range_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='rangemembership',
            index=models.Index(fields=['workspace', 'range'], name='membership_workspace_range_idx'),
        ),
    ]
