# Generated by Django 5.2.17 on 2026-09-21 17:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_workspace_region_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('code', models.CharField(blank=True, editable=False, max_length=35, unique=True, verbose_name='کد مشتری')),
                ('customer_type', models.CharField(choices=[('buyer', 'خریدار'), ('tenant', 'مستأجر')], max_length=10, verbose_name='نوع مشتری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('completed', 'تکمیل\u200cشده'), ('archived', 'بایگانی\u200cشده')], default='active', max_length=10, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_valuable', models.BooleanField(default=False, verbose_name='ارزشمند')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداقل مساحت (متر مربع)')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداکثر مساحت (متر مربع)')),
                ('min_building_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداقل سن بنا')),
                ('max_building_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداکثر سن بنا')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد اتاق خواب')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='بودجه خرید (تومان)')),
                ('budget_status', models.CharField(blank=True, choices=[('cash', 'کاملاً نقد'), ('cash_plus_property', 'بخشی نقد + آپارتمان')], default=None, max_length=20, null=True, verbose_name='وضعیت بودجه')),
                ('deposit_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='بودجه ودیعه (تومان)')),
                ('monthly_rent_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='بودجه اجاره ماهانه (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='مشاور مسئول')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='CustomerRegionPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_preferences', to='customers.customer', verbose_name='مشتری')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_preferences', to='locations.region', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'منطقه مورد نظر مشتری',
                'verbose_name_plural': 'مناطق مورد نظر مشتری',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_regions',
            field=models.ManyToManyField(blank=True, related_name='interested_customers', through='customers.CustomerRegionPreference', to='locations.region', verbose_name='مناطق مورد نظر'),
        ),
        migrations.CreateModel(
            name='CustomerValuableReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('reason', models.CharField(max_length=150, verbose_name='دلیل ارزشمندی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuable_reasons', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'دلیل ارزشمندی مشتری',
                'verbose_name_plural': 'دلایل ارزشمندی مشتری',
            },
        ),
        migrations.AddConstraint(
            model_name='customerregionpreference',
            constraint=models.UniqueConstraint(fields=('customer', 'region'), name='customer_unique_region'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'status'], name='customer_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'customer_type'], name='customer_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'assigned_to'], name='customer_ws_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('min_area__gte', 0), ('min_area__isnull', True), _connector='OR'), name='customer_min_area_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('max_area__gte', 0), ('max_area__isnull', True), _connector='OR'), name='customer_max_area_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('min_building_age__gte', 0), ('min_building_age__isnull', True), _connector='OR'), name='customer_min_building_age_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('max_building_age__gte', 0), ('max_building_age__isnull', True), _connector='OR'), name='customer_max_building_age_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0), ('bedrooms__isnull', True), _connector='OR'), name='customer_bedrooms_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('budget__gte', 0), ('budget__isnull', True), _connector='OR'), name='customer_budget_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_budget__gte', 0), ('deposit_budget__isnull', True), _connector='OR'), name='customer_deposit_budget_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent_budget__gte', 0), ('monthly_rent_budget__isnull', True), _connector='OR'), name='customer_monthly_rent_budget_nonneg', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('min_area__isnull', True), ('max_area__isnull', True), ('min_area__lte', models.F('max_area')), _connector='OR'), name='customer_area_bounds', violation_error_message='حداقل مساحت نباید بیشتر از حداکثر باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('min_building_age__isnull', True), ('max_building_age__isnull', True), ('min_building_age__lte', models.F('max_building_age')), _connector='OR'), name='customer_age_bounds', violation_error_message='حداقل سن بنا نباید بیشتر از حداکثر باشد.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_type', 'buyer'), ('deposit_budget__isnull', True), ('monthly_rent_budget__isnull', True)), models.Q(('budget__isnull', True), ('budget_status__isnull', True), ('customer_type', 'tenant')), _connector='OR'), name='customer_type_financials', violation_error_message='اطلاعات مالی با نوع مشتری سازگار نیست.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('budget_status__isnull', True), ('budget_status__in', ['cash', 'cash_plus_property']), _connector='OR'), name='customer_budget_status', violation_error_message='وضعیت بودجه معتبر نیست.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'completed', 'archived'])), name='customer_valid_status', violation_error_message='وضعیت مشتری معتبر نیست.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='customer_code_not_empty', violation_error_message='کد مشتری الزامی است.'),
        ),
        migrations.AddConstraint(
            model_name='customervaluablereason',
            constraint=models.UniqueConstraint(fields=('customer', 'reason'), name='customer_unique_reason'),
        ),
    ]
