# Generated by Django 5.2.17 on 2026-09-25 17:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def validate_existing_customers(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    rows = Customer.objects.using(schema_editor.connection.alias)
    checks = {
        'min_area_missing': models.Q(min_area__isnull=True),
        'max_area_missing': models.Q(max_area__isnull=True),
        'bedrooms_missing': models.Q(bedrooms__isnull=True),
        'buyer_budget_missing': models.Q(customer_type='buyer', budget__isnull=True),
        'tenant_deposit_missing': models.Q(customer_type='tenant', deposit_budget__isnull=True),
        'tenant_rent_missing': models.Q(customer_type='tenant', monthly_rent_budget__isnull=True),
        'zero_preferences': models.Q(region_preferences__isnull=True),
        'incompatible_financials': (
            models.Q(customer_type='buyer') & (models.Q(deposit_budget__isnull=False) | models.Q(monthly_rent_budget__isnull=False))
            | models.Q(customer_type='tenant') & (models.Q(budget__isnull=False) | models.Q(budget_status__isnull=False))
        ),
        'invalid_bounds': models.Q(min_area__gt=models.F('max_area')),
    }
    for field in ('min_area', 'max_area', 'bedrooms', 'budget', 'deposit_budget', 'monthly_rent_budget'):
        checks[f'{field}_negative'] = models.Q(**{f'{field}__lt': 0})
    counts = {name: rows.filter(condition).distinct().count() for name, condition in checks.items()}
    Preference = apps.get_model('customers', 'CustomerRegionPreference')
    counts['invalid_region_workspace'] = Preference.objects.using(schema_editor.connection.alias).filter(
        ~models.Q(region__workspace_id=models.F('customer__workspace_id'))
        | ~models.Q(region__city__workspace_id=models.F('customer__workspace_id')),
    ).values('customer_id').distinct().count()
    invalid = {name: count for name, count in counts.items() if count}
    if invalid:
        raise RuntimeError(f'Customer canonical migration blocked; no business values inferred: {invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0003_workspace_region_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_customers, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='customer',
            name='customer_type_financials',
        ),
        migrations.AddField(
            model_name='customer',
            name='all_regions',
            field=models.BooleanField(default=False, verbose_name='همه مناطق فعال مجموعه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='max_area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداکثر مساحت (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='min_area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='حداقل مساحت (متر مربع)'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('budget__isnull', False), ('customer_type', 'buyer'), ('deposit_budget__isnull', True), ('monthly_rent_budget__isnull', True)), models.Q(('budget__isnull', True), ('budget_status__isnull', True), ('customer_type', 'tenant'), ('deposit_budget__isnull', False), ('monthly_rent_budget__isnull', False)), _connector='OR'), name='customer_type_financials', violation_error_message='اطلاعات مالی با نوع مشتری سازگار نیست.'),
        ),
    ]
