# Generated by Django 5.2.17 on 2026-10-06 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_workspace_region_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('scheduled_for', models.DateTimeField(verbose_name='زمان برنامه\u200cریزی')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='تمام\u200cروز')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام\u200cشده'), ('cancelled', 'لغوشده')], default='pending', max_length=9, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'کار شخصی',
                'verbose_name_plural': 'کارهای شخصی',
                'indexes': [models.Index(fields=['workspace', 'owner', 'status', 'scheduled_for'], name='manual_owner_status_time'), models.Index(fields=['workspace', 'owner', 'scheduled_for'], name='manual_owner_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'done', 'cancelled'])), name='manual_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'done')), models.Q(('completed_at__isnull', True), ('status__in', ['pending', 'cancelled'])), _connector='OR'), name='manual_completion_valid')],
            },
        ),
    ]
