# Generated by Django 5.2.17 on 2026-09-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_workspace_owner',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند این کاربر خریدار و مالک اصلی فضای کاری است.', verbose_name='یوزر اصلی مجموعه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agency_manager', 'مدیر املاک'), ('range_manager', 'مدیر رنج'), ('consultant', 'مشاور'), ('secretary', 'منشی'), ('admin', 'ادمین')], max_length=30, verbose_name='نقش'),
        ),
    ]
