# Generated by Django 5.2.17 on 2026-09-17 11:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_workspace_owner_alter_user_is_active_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0002_workspace_region_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='نام کاربری باید در مجموعه یکتا باشد.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='نام کاربری'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('workspace', 'username'), name='unique_username_per_workspace'),
        ),
    ]
