# Generated by Django 5.2.17 on 2026-09-21 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_workspace_region_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('code', models.CharField(blank=True, editable=False, max_length=35, unique=True, verbose_name='کد فایل')),
                ('transaction_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, verbose_name='نوع معامله')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('sold', 'فروخته\u200cشده'), ('rented', 'اجاره\u200cداده\u200cشده'), ('archived', 'بایگانی\u200cشده')], default='active', max_length=10, verbose_name='وضعیت')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن مالک')),
                ('visit_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن هماهنگی بازدید')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='مساحت (متر مربع)')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد اتاق خواب')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد طبقات')),
                ('units_per_floor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد واحد در طبقه')),
                ('unit_floor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='طبقه واحد')),
                ('building_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='سن بنا (سال)')),
                ('parking', models.BooleanField(blank=True, default=None, null=True, verbose_name='پارکینگ')),
                ('storage', models.BooleanField(blank=True, default=None, null=True, verbose_name='انباری')),
                ('elevator', models.BooleanField(blank=True, default=None, null=True, verbose_name='آسانسور')),
                ('balcony', models.BooleanField(blank=True, default=None, null=True, verbose_name='بالکن')),
                ('price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='قیمت هر متر مربع (تومان)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='قیمت کل (تومان)')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='ودیعه (تومان)')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='اجاره ماهانه (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('source', models.CharField(choices=[('manual', 'دستی')], default='manual', max_length=30, verbose_name='منبع فایل')),
                ('is_valuable', models.BooleanField(default=False, verbose_name='ارزشمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_files', to=settings.AUTH_USER_MODEL, verbose_name='مشاور مسئول')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_files', to='locations.city', verbose_name='شهر')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_files', to='locations.region', verbose_name='منطقه')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_files', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'فایل ملکی',
                'verbose_name_plural': 'فایل\u200cهای ملکی',
            },
        ),
        migrations.CreateModel(
            name='PropertyFileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('reference', models.CharField(max_length=2048, verbose_name='نشانی یا مرجع تصویر')),
                ('sort_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('property_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertyfile', verbose_name='فایل ملکی')),
            ],
            options={
                'verbose_name': 'تصویر فایل',
                'verbose_name_plural': 'تصاویر فایل',
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFileValuableReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('reason', models.CharField(max_length=150, verbose_name='دلیل ارزشمندی')),
                ('property_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuable_reasons', to='properties.propertyfile', verbose_name='فایل ملکی')),
            ],
            options={
                'verbose_name': 'دلیل ارزشمندی فایل',
                'verbose_name_plural': 'دلایل ارزشمندی فایل',
            },
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['workspace', 'status'], name='pf_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['workspace', 'transaction_type'], name='pf_workspace_type_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['workspace', 'region'], name='pf_workspace_region_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['workspace', 'assigned_to'], name='pf_workspace_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('area__gte', 0), ('area__isnull', True), _connector='OR'), name='pf_area_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0), ('bedrooms__isnull', True), _connector='OR'), name='pf_bedrooms_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('total_floors__gte', 0), ('total_floors__isnull', True), _connector='OR'), name='pf_total_floors_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_floor__gte', 0), ('units_per_floor__isnull', True), _connector='OR'), name='pf_units_per_floor_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('unit_floor__gte', 0), ('unit_floor__isnull', True), _connector='OR'), name='pf_unit_floor_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('building_age__gte', 0), ('building_age__isnull', True), _connector='OR'), name='pf_building_age_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_square_meter__gte', 0), ('price_per_square_meter__isnull', True), _connector='OR'), name='pf_price_per_square_meter_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0), ('total_price__isnull', True), _connector='OR'), name='pf_total_price_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0), ('deposit_amount__isnull', True), _connector='OR'), name='pf_deposit_amount_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gte', 0), ('monthly_rent__isnull', True), _connector='OR'), name='pf_monthly_rent_nonnegative', violation_error_message='مقدار نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_amount__isnull', True), ('monthly_rent__isnull', True), ('transaction_type', 'sale')), models.Q(('price_per_square_meter__isnull', True), ('total_price__isnull', True), ('transaction_type', 'rent')), _connector='OR'), name='pf_transaction_financials', violation_error_message='مبالغ باید با نوع معامله سازگار باشند.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'sold', 'rented', 'archived'])), name='pf_valid_status', violation_error_message='وضعیت فایل معتبر نیست.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='pf_code_not_empty', violation_error_message='کد فایل الزامی است.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfileimage',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='pf_image_order_nonnegative', violation_error_message='ترتیب تصویر نمی\u200cتواند منفی باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfilevaluablereason',
            constraint=models.UniqueConstraint(fields=('property_file', 'reason'), name='pf_unique_valuable_reason'),
        ),
    ]
