# Generated by Django 5.2.17 on 2026-09-24 12:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def prepare_canonical_files(apps, schema_editor):
    files = apps.get_model('properties', 'PropertyFile').objects.using(schema_editor.connection.alias)
    Q, F = models.Q, models.F
    checks = {
        'region_missing': Q(region__isnull=True),
        'area_missing_or_nonpositive': Q(area__isnull=True) | Q(area__lte=0),
        'bedrooms_missing_or_negative': Q(bedrooms__isnull=True) | Q(bedrooms__lt=0),
        'sale_total_missing': Q(transaction_type='sale', total_price__isnull=True),
        'rent_amount_missing': Q(transaction_type='rent') & (Q(deposit_amount__isnull=True) | Q(monthly_rent__isnull=True)),
        'incompatible_finances': (Q(transaction_type='sale') & (Q(deposit_amount__isnull=False) | Q(monthly_rent__isnull=False))) | (Q(transaction_type='rent') & (Q(total_price__isnull=False) | Q(price_per_square_meter__isnull=False))),
        'negative_money': Q(total_price__lt=0) | Q(deposit_amount__lt=0) | Q(monthly_rent__lt=0),
        'invalid_type': ~Q(transaction_type__in=['sale', 'rent']),
        'invalid_relationships': ~Q(region__workspace_id=F('workspace_id')) | ~Q(city__workspace_id=F('workspace_id')) | ~Q(region__city_id=F('city_id')) | ~Q(assigned_to__workspace_id=F('workspace_id')) | ~Q(assigned_to__role='consultant'),
    }
    counts = {name: files.filter(condition).count() for name, condition in checks.items()}
    if any(counts.values()):
        raise RuntimeError(f'Canonical PropertyFile migration blocked; repair business data: {counts}')
    # Two passes: detect every blocker before changing any stored derived values.
    for row in files.filter(transaction_type='sale').iterator():
        n, d = row.total_price.as_integer_ratio()
        a, b = row.area.as_integer_ratio()
        value = Decimal(((n * b) // (d * a * 1_000_000)) * 1_000_000)
        if value >= Decimal('1000000000000000000'):
            raise RuntimeError('Canonical PropertyFile derived price exceeds storage precision.')
    for row in files.filter(transaction_type='sale').iterator():
        n, d = row.total_price.as_integer_ratio()
        a, b = row.area.as_integer_ratio()
        files.filter(pk=row.pk).update(price_per_square_meter=Decimal(((n * b) // (d * a * 1_000_000)) * 1_000_000))


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0003_workspace_region_policy'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(prepare_canonical_files, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='propertyfile',
            name='pf_transaction_financials',
        ),
        migrations.AlterField(
            model_name='propertyfile',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مساحت (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='propertyfile',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='propertyfile',
            name='price_per_square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='قیمت هر متر مربع (تومان)'),
        ),
        migrations.AlterField(
            model_name='propertyfile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_files', to='locations.region', verbose_name='منطقه'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(('area__gt', 0)), name='pf_area_positive', violation_error_message='مساحت باید بیشتر از صفر باشد.'),
        ),
        migrations.AddConstraint(
            model_name='propertyfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_amount__isnull', True), ('monthly_rent__isnull', True), ('price_per_square_meter__isnull', False), ('total_price__isnull', False), ('transaction_type', 'sale')), models.Q(('deposit_amount__isnull', False), ('monthly_rent__isnull', False), ('price_per_square_meter__isnull', True), ('total_price__isnull', True), ('transaction_type', 'rent')), _connector='OR'), name='pf_transaction_financials', violation_error_message='مبالغ باید با نوع معامله سازگار باشند.'),
        ),
    ]
