# Generated by Django 5.2.17 on 2026-09-12 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_workspace_region_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('divar', 'دیوار')], default='manual', max_length=20, verbose_name='منبع')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه خارجی')),
                ('external_slug', models.CharField(blank=True, max_length=100, verbose_name='شناسه متنی خارجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('divar', 'دیوار')], default='manual', max_length=20, verbose_name='منبع')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه خارجی')),
                ('external_slug', models.CharField(blank=True, max_length=100, verbose_name='شناسه متنی خارجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='locations.city', verbose_name='شهر')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['workspace', 'is_active'], name='city_workspace_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_city_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['workspace', 'city', 'is_active'], name='region_workspace_city_idx'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('workspace', 'city', 'name'), name='unique_region_per_city_workspace'),
        ),
    ]
