# Generated by Django 5.2.17 on 2026-09-25 18:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن مساحت')),
                ('bedrooms', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن اتاق خواب')),
                ('building_age', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن سن بنا')),
                ('region', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن منطقه')),
                ('parking', models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن پارکینگ')),
                ('elevator', models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن آسانسور')),
                ('storage', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن انباری')),
                ('balcony', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.')], verbose_name='وزن بالکن')),
                ('minimum_score', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='مقدار نمی\u200cتواند منفی باشد.'), django.core.validators.MaxValueValidator(100, message='امتیاز نباید بیشتر از ۱۰۰ باشد.')], verbose_name='حداقل امتیاز')),
                ('sale_budget_lower_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.80'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(1)], verbose_name='نسبت پایین بودجه خرید')),
                ('sale_budget_upper_ratio', models.DecimalField(decimal_places=4, default=Decimal('1.20'), max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='نسبت بالای بودجه خرید')),
                ('rent_per_100m_deposit', models.DecimalField(decimal_places=2, default=Decimal('3000000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='اجاره ماهانه معادل صد میلیون تومان ودیعه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات پایه تطبیق',
                'verbose_name_plural': 'تنظیمات پایه تطبیق',
                'constraints': [models.CheckConstraint(condition=models.Q(('area__gte', 0)), name='matching_area_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0)), name='matching_bedrooms_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('building_age__gte', 0)), name='matching_building_age_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('region__gte', 0)), name='matching_region_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('parking__gte', 0)), name='matching_parking_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('elevator__gte', 0)), name='matching_elevator_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('storage__gte', 0)), name='matching_storage_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('balcony__gte', 0)), name='matching_balcony_nonneg', violation_error_message='وزن نمی\u200cتواند منفی باشد.'), models.CheckConstraint(condition=models.Q(('area__gt', 0), ('bedrooms__gt', 0), ('building_age__gt', 0), ('region__gt', 0), ('parking__gt', 0), ('elevator__gt', 0), ('storage__gt', 0), ('balcony__gt', 0), _connector='OR'), name='matching_positive_weight', violation_error_message='حداقل یک وزن باید بیشتر از صفر باشد.'), models.CheckConstraint(condition=models.Q(('minimum_score__gte', 0), ('minimum_score__lte', 100)), name='matching_score_range', violation_error_message='حداقل امتیاز باید بین صفر و صد باشد.'), models.CheckConstraint(condition=models.Q(('sale_budget_lower_ratio__gt', 0), ('sale_budget_lower_ratio__lte', 1), ('sale_budget_upper_ratio__gte', 1), ('sale_budget_lower_ratio__lte', models.F('sale_budget_upper_ratio'))), name='matching_sale_ratios', violation_error_message='نسبت\u200cهای بودجه معتبر نیستند.'), models.CheckConstraint(condition=models.Q(('rent_per_100m_deposit__gt', 0)), name='matching_rent_positive', violation_error_message='معادل اجاره باید بیشتر از صفر باشد.')],
            },
        ),
    ]
