# Generated by Django 5.2.17 on 2026-10-02 14:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_canonical_completeness'),
        ('matching', '0001_initial'),
        ('properties', '0002_canonical_completeness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('user_status', models.CharField(choices=[('new', 'جدید'), ('seen', 'دیده\u200cشده'), ('done', 'انجام\u200cشده'), ('rejected', 'ردشده')], default='new', max_length=8, verbose_name='وضعیت دستی')),
                ('current_score', models.DecimalField(blank=True, decimal_places=30, max_digits=33, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز فعلی')),
                ('score_at_last_view', models.DecimalField(blank=True, decimal_places=30, max_digits=33, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز آخرین مشاهده')),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='آستانه آخرین ارزیابی')),
                ('formula_version', models.CharField(max_length=40, verbose_name='نسخه فرمول')),
                ('is_viewer_valid', models.BooleanField(default=True, verbose_name='اعتبار ارتباط مشاور')),
                ('is_source_valid', models.BooleanField(default=True, verbose_name='اعتبار منابع')),
                ('is_currently_recommended', models.BooleanField(default=True, verbose_name='پیشنهاد فعلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('last_evaluated_at', models.DateTimeField(verbose_name='آخرین ارزیابی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_recommendations', to='customers.customer', verbose_name='مشتری')),
                ('property_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_recommendations', to='properties.propertyfile', verbose_name='فایل')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='مشاور دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پیشنهاد تطبیق',
                'verbose_name_plural': 'پیشنهادهای تطبیق',
                'indexes': [models.Index(fields=['viewer', 'user_status'], name='recommendation_view_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('viewer', 'property_file', 'customer'), name='unique_viewer_match_pair'), models.CheckConstraint(condition=models.Q(('user_status__in', ['new', 'seen', 'done', 'rejected'])), name='recommendation_status_valid'), models.CheckConstraint(condition=models.Q(('current_score__isnull', True), models.Q(('current_score__gte', 0), ('current_score__lte', 100)), _connector='OR'), name='recommendation_score_range'), models.CheckConstraint(condition=models.Q(('score_at_last_view__isnull', True), models.Q(('score_at_last_view__gte', 0), ('score_at_last_view__lte', 100)), _connector='OR'), name='recommendation_view_score_range'), models.CheckConstraint(condition=models.Q(('minimum_score__gte', 0), ('minimum_score__lte', 100)), name='recommendation_threshold_range'), models.CheckConstraint(condition=models.Q(('is_currently_recommended', False), models.Q(('current_score__isnull', False), ('is_source_valid', True), ('is_viewer_valid', True)), _connector='OR'), name='recommendation_valid_flags')],
            },
        ),
    ]
