# Generated by Django 5.2.17 on 2026-10-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_match_recommendation'),
        ('organizations', '0003_workspace_region_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecommendation',
            name='last_generation_event',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='آخرین رویداد پردازش\u200cشده'),
        ),
        migrations.CreateModel(
            name='RecommendationWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'فایل'), ('customer', 'مشتری'), ('profile', 'تنظیمات مشاور'), ('region', 'منطقه'), ('workspace', 'مجموعه')], max_length=10, verbose_name='نوع کار')),
                ('target_id', models.UUIDField(null=True, verbose_name='شناسه هدف')),
                ('material', models.BooleanField(default=True, verbose_name='تغییر مؤثر')),
                ('phase', models.CharField(default='existing', max_length=10, verbose_name='مرحله')),
                ('after_id', models.UUIDField(null=True, verbose_name='نشانگر ادامه')),
                ('file_id', models.UUIDField(null=True, verbose_name='فایل جاری')),
                ('customer_after', models.UUIDField(null=True, verbose_name='نشانگر مشتری')),
                ('step', models.PositiveIntegerField(default=0, verbose_name='گام')),
                ('completed', models.BooleanField(default=False, verbose_name='پایان\u200cیافته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'کار بازبینی پیشنهادها',
                'verbose_name_plural': 'کارهای بازبینی پیشنهادها',
                'indexes': [models.Index(fields=['completed', 'id'], name='matching_pending_work_idx'), models.Index(fields=['workspace', 'kind', 'target_id', 'id'], name='matching_work_target_idx')],
            },
        ),
    ]
