# Generated by Django 5.2.17 on 2026-10-02 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_canonical_completeness'),
        ('matching', '0003_recommendation_generation'),
        ('properties', '0002_canonical_completeness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('manual_status', models.CharField(choices=[('new', 'جدید'), ('seen', 'دیده\u200cشده'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'ردشده')], default='new', max_length=8, verbose_name='وضعیت پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_requests', to='customers.customer', verbose_name='مشتری')),
                ('participant_a', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده اول')),
                ('participant_b', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده دوم')),
                ('property_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_requests', to='properties.propertyfile', verbose_name='فایل')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
            },
        ),
        migrations.CreateModel(
            name='CollaborationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creation_event', to='matching.collaborationrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'رویداد درخواست همکاری',
                'verbose_name_plural': 'رویدادهای درخواست همکاری',
            },
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.UniqueConstraint(fields=('property_file', 'customer', 'participant_a', 'participant_b'), name='unique_collaboration_pair'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('participant_a__lt', models.F('participant_b'))), name='collaboration_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient', models.F('participant_b')), ('requester', models.F('participant_a'))), models.Q(('recipient', models.F('participant_a')), ('requester', models.F('participant_b'))), _connector='OR'), name='collaboration_participants'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('manual_status__in', ['new', 'seen', 'accepted', 'rejected'])), name='collaboration_status_valid'),
        ),
    ]
