# Generated by Django 5.2.17 on 2026-09-12 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=150, verbose_name='نام مجموعه')),
                ('slug', models.SlugField(help_text='برای ساخت آدرس اختصاصی مجموعه استفاده می\u200cشود.', max_length=100, unique=True, verbose_name='شناسه آدرس')),
                ('customer_type', models.CharField(choices=[('agency_manager', 'مدیر املاک'), ('range_manager', 'مدیر رنج'), ('consultant', 'مشاور')], max_length=30, verbose_name='نوع خریدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مجموعه',
                'verbose_name_plural': 'مجموعه\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
