# Generated by Django 5.2.17 on 2026-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='region_mode',
            field=models.CharField(choices=[('none', 'بدون تفکیک منطقه'), ('custom', 'منطقه\u200cبندی اختصاصی'), ('divar', 'منطقه\u200cبندی دیوار')], default='custom', max_length=20, verbose_name='نوع منطقه\u200cبندی'),
        ),
    ]
