# Generated by Django 5.2.17 on 2026-09-24 12:30

from django.db import migrations, models


def unconfigure_legacy_none(apps, schema_editor):
    workspace = apps.get_model('organizations', 'Workspace')
    rows = workspace.objects.using(schema_editor.connection.alias)
    if rows.exclude(region_mode__in=['none', 'custom', 'divar']).exclude(region_mode__isnull=True).exists():
        raise RuntimeError('Unexpected Workspace region_mode; review data before migrating.')
    rows.filter(region_mode='none').update(region_mode=None)


def restore_legacy_none(apps, schema_editor):
    workspace = apps.get_model('organizations', 'Workspace')
    workspace.objects.using(schema_editor.connection.alias).filter(region_mode__isnull=True).update(region_mode='none')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_workspace_region_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='region_mode',
            field=models.CharField(blank=True, choices=[('custom', 'منطقه\u200cبندی اختصاصی'), ('divar', 'منطقه\u200cبندی دیوار')], default=None, max_length=20, null=True, verbose_name='نوع منطقه\u200cبندی'),
        ),
        migrations.RunPython(unconfigure_legacy_none, restore_legacy_none),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('region_mode__isnull', True), ('region_mode__in', ['custom', 'divar']), _connector='OR'), name='workspace_valid_region_mode', violation_error_message='نوع منطقه\u200cبندی معتبر نیست.'),
        ),
    ]
