# Generated by Django 5.2.17 on 2026-10-06 20:53

import apps.notifications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_workspace_region_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('kind', models.CharField(choices=[('match_recommendation', 'پیشنهاد تطبیق'), ('collaboration_request', 'درخواست همکاری'), ('chat_message', 'پیام گفتگو'), ('import_review', 'بررسی ورود اطلاعات'), ('voice_review', 'بررسی اطلاعات صوتی')], max_length=24, verbose_name='نوع')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('message', models.CharField(max_length=400, verbose_name='پیام')),
                ('action_url', models.CharField(max_length=240, validators=[apps.notifications.models.validate_action_url], verbose_name='پیوند')),
                ('source_type', models.CharField(blank=True, default='', max_length=40, verbose_name='نوع منبع')),
                ('source_id', models.UUIDField(blank=True, null=True, verbose_name='شناسه منبع')),
                ('event_key', models.CharField(max_length=200, verbose_name='کلید رویداد')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_read_time'), models.Index(fields=['recipient', 'kind', 'created_at'], name='notification_kind_time')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='notification_recipient_event'), models.CheckConstraint(condition=models.Q(('kind__in', ['match_recommendation', 'collaboration_request', 'chat_message', 'import_review', 'voice_review'])), name='notification_kind_valid')],
            },
        ),
    ]
