# Generated by Django 5.2.17 on 2026-10-08 08:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_workspace_region_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('participant_a_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خواندن عضو اول')),
                ('participant_b_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خواندن عضو دوم')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='آخرین فعالیت')),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_a', to=settings.AUTH_USER_MODEL, verbose_name='عضو اول')),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_b', to=settings.AUTH_USER_MODEL, verbose_name='عضو دوم')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.workspace', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'گفتگوی خصوصی',
                'verbose_name_plural': 'گفتگوهای خصوصی',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='متن')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='زمان ارسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.conversation', verbose_name='گفتگو')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'participant_a', 'updated_at'], name='chat_a_activity'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'participant_b', 'updated_at'], name='chat_b_activity'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('workspace', 'participant_a', 'participant_b'), name='chat_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('participant_a__lt', models.F('participant_b'))), name='chat_ordered_pair'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at', 'id'], name='chat_message_history'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='chat_message_not_empty'),
        ),
    ]
